namespace JoyZoning.Domain.Orchestration;

public sealed record JoyZoningEndpointDescriptor(
    string Id,
    string Method,
    string Path,
    string Purpose,
    string? InputSchema,
    string? OutputSchema,
    bool AgentSafe);

public static class JoyZoningEndpointRegistry
{
    public static readonly IReadOnlyList<JoyZoningEndpointDescriptor> Endpoints =
    [
        new("health", "GET", "/api/health",
            "Check control-plane availability and high-level runtime health.",
            null, "HealthResponse", true),
        new("list-sessions", "GET", "/api/sessions",
            "List canonical JoyZoning operator sessions.",
            null, "OperatorSession[]", true),
        new("create-session", "POST", "/api/sessions",
            "Create a JoyZoning operator session.",
            "CreateSessionRequest", "OperatorSession", true),
        new("get-session", "GET", "/api/sessions/{id}",
            "Read one operator session.",
            null, "OperatorSession", true),
        new("list-tasks", "GET", "/api/tasks?sessionId={sessionId}",
            "List tasks for a session workspace.",
            null, "WorkTask[]", true),
        new("get-task", "GET", "/api/tasks/{id}",
            "Read one task by id.",
            null, "WorkTask", true),
        new("create-task", "POST", "/api/tasks",
            "Create a task under an operator session.",
            "CreateTaskRequest", "WorkTask", true),
        new("update-task-status", "PUT", "/api/tasks/{id}/status",
            "Update task status; agents cannot use this to mark Complete.",
            "UpdateTaskStatusRequest", "WorkTask", false),
        new("dispatch-task", "POST", "/api/tasks/{id}/dispatch",
            "Dispatch a task to an executor lease.",
            "DispatchTaskRequest", "ExecutionSession", false),
        new("get-task-lease", "GET", "/api/tasks/{id}/lease",
            "Read active execution lease for a task.",
            null, "ExecutionLease", true),
        new("lease-heartbeat", "POST", "/api/tasks/{id}/lease/heartbeat",
            "Record an agent heartbeat for an active lease.",
            "LeaseHeartbeatRequest", "ExecutionLease", true),
        new("lease-agent-status", "POST", "/api/tasks/{id}/lease/agent-status",
            "Move an agent lease through allowed agent-owned states.",
            "AgentLeaseStatusRequest", "ExecutionLease", true),
        new("submit-verification", "POST", "/api/tasks/{id}/verification",
            "Attach local verification evidence and request human review when passing.",
            "SubmitVerificationRequest", "ExecutionLease", true),
        new("revoke-lease", "POST", "/api/tasks/{id}/lease/revoke",
            "Human revoke of an active lease.",
            "RevokeLeaseRequest", "ExecutionLease", false),
        new("merge-lease", "POST", "/api/tasks/{id}/lease/merge",
            "Human merge after ReadyForReview and passing verification.",
            null, "ExecutionLease", false),
        new("import-kanban", "POST", "/api/tasks/import-kanban",
            "Import kanban tasks for a session.",
            "ImportKanbanRequest", "ImportKanbanResult", false),
        new("manager-message", "POST", "/api/manager/message",
            "Send a manager chat message through Hermes.",
            "ManagerMessageRequest", "ManagerMessageResponse", true),
        new("get-execution", "GET", "/api/executions/{id}",
            "Read one execution session.",
            null, "ExecutionSession", true),
        new("list-interrupted-executions", "GET", "/api/executions/interrupted",
            "List executions that can be resumed or cancelled.",
            null, "ExecutionSession[]", true),
        new("resume-execution", "POST", "/api/executions/{id}/resume",
            "Resume an interrupted execution.",
            null, "ExecutionSession", false),
        new("cancel-execution", "POST", "/api/executions/{id}/cancel",
            "Cancel an interrupted execution.",
            null, "ExecutionSession", false),
        new("pending-approvals", "GET", "/api/approvals/pending",
            "List pending approval requests.",
            null, "ApprovalRequest[]", true),
        new("resolve-approval", "POST", "/api/approvals/{id}/resolve",
            "Resolve an approval request with human scope.",
            "ResolveApprovalRequest", "ApprovalRequest", false),
        new("events", "GET", "/api/events",
            "Query control-plane events by cursor, correlation, or type.",
            null, "JoyEvent[]", true),
        new("workspace-tree", "GET", "/api/workspace/tree",
            "List workspace files.",
            null, "WorkspaceTreeEntry[]", true),
        new("workspace-changed", "GET", "/api/workspace/changed",
            "List changed workspace files.",
            null, "ChangedFile[]", true),
        new("workspace-diff", "GET", "/api/workspace/diff",
            "Read git diff for one workspace path.",
            null, "WorkspaceDiffResponse", true),
        new("task-live", "GET", "/api/tasks/{id}/live",
            "Read live mirror state for an executing task.",
            null, "WorkspaceLiveResponse", true),
        new("task-live-refresh", "POST", "/api/tasks/{id}/live/refresh",
            "Refresh live mirror state for an active task lease.",
            null, "WorkspaceLiveResponse", true),
        new("task-workspace-changed", "GET", "/api/tasks/{id}/workspace/changed",
            "List changed files in a task worktree or session workspace.",
            null, "TaskWorkspaceChangedResponse", true),
        new("task-workspace-tree", "GET", "/api/tasks/{id}/workspace/tree",
            "List files in a task worktree or session workspace.",
            null, "TaskWorkspaceTreeResponse", true),
        new("task-workspace-diff", "GET", "/api/tasks/{id}/workspace/diff",
            "Read git diff for one task workspace path.",
            null, "TaskWorkspaceDiffResponse", true),
        new("hermes-health", "GET", "/api/hermes/health",
            "Check Hermes connectivity.",
            null, "HermesHealthResponse", true),
        new("hermes-ensure", "POST", "/api/hermes/ensure",
            "Ensure Hermes connectivity prerequisites.",
            null, "HermesEnsureResponse", false),
        new("hermes-dashboard", "GET", "/api/hermes/dashboard",
            "Read Hermes dashboard connectivity status.",
            null, "HermesDashboardResponse", true),
        new("hermes-ensure-dashboard", "POST", "/api/hermes/ensure-dashboard",
            "Ensure Hermes dashboard credentials and gateway readiness.",
            "EnsureDashboardRequest", "HermesDashboardEnsureResponse", false),
        new("hermes-refresh-dashboard-token", "POST", "/api/hermes/refresh-dashboard-token",
            "Refresh Hermes dashboard token.",
            null, "HermesDashboardEnsureResponse", false),
        new("hermes-connector-status", "GET", "/api/hermes/connector-status",
            "Read Hermes connector diagnostics.",
            null, "HermesConnectorDiagnosticsResponse", true),
        new("config-get", "GET", "/api/config",
            "Read control-plane configuration.",
            null, "AppSettingsDto", true),
        new("config-save", "PUT", "/api/config",
            "Save control-plane configuration.",
            "AppSettingsDto", "AppSettingsDto", false),
        new("kanban-sync-status", "GET", "/api/kanban/sync-status",
            "Read kanban sync status.",
            null, "KanbanSyncStatusResponse", true),
        new("broccoliq-health", "GET", "/api/broccoliq/health",
            "Read BroccoliQ bridge health.",
            null, "BroccoliQHealthResponse", true),
        new("broccoliq-backfill", "POST", "/api/broccoliq/backfill",
            "Backfill BroccoliQ hive from control-plane events.",
            null, "BroccoliQBackfillResponse", false),
        new("broccoliq-flush", "POST", "/api/broccoliq/flush",
            "Flush BroccoliQ bridge mirror queue.",
            null, "BroccoliQFlushResponse", false),
        new("broccoliq-audit", "GET", "/api/broccoliq/audit",
            "Query recent BroccoliQ hive audit events.",
            null, "BroccoliQAuditResponse", true),
        new("broccoliq-tasks", "GET", "/api/broccoliq/tasks",
            "Query BroccoliQ hive task records.",
            null, "BroccoliQTasksResponse", true),
        new("consolidate-sessions", "POST", "/api/sessions/consolidate",
            "Consolidate duplicate operator sessions for one workspace.",
            null, "SessionConsolidationResult", false),
        new("open-workspace-path", "POST", "/api/sessions/open-path",
            "Open a workspace path in the OS file manager.",
            "OpenWorkspacePathRequest", "OpenWorkspacePathResponse", false),
        new("session-parallel-workers", "GET", "/api/sessions/{id}/parallel-workers",
            "Read parallel worker mirror state for a session.",
            null, "ParallelWorkersMirrorResponse", true),
        new("session-merge-queue", "GET", "/api/sessions/{id}/merge-queue",
            "Read merge queue mirror state for a session.",
            null, "MergeQueueMirrorResponse", true),
        new("session-authority-reconcile", "POST", "/api/sessions/{id}/authority/reconcile",
            "Reconcile session authority and autopilot state.",
            null, "AuthorityReconcileResponse", false),
        new("authority-reconcile-ready", "POST", "/api/authority/reconcile-ready",
            "Reconcile ready-for-review authority across sessions.",
            null, "AuthorityReconcileResponse", false),
        new("operational-modes", "GET", "/api/operational-modes",
            "Read operational mode metadata and guardrails.",
            null, "OperationalModesResponse", true),
        new("worker-decision-preflight", "GET", "/api/sessions/{sessionId}/workers/{executionSessionId}/decision-preflight",
            "Preflight accept/revoke/inspect decisions for a worker execution.",
            null, "WorkerDecisionPreflightResponse", true),
        new("watch-bootstrap", "GET", "/api/watch/bootstrap",
            "Bootstrap payload for the watch operator UI.",
            null, "WatchBootstrapResponse", true),
        new("lease-agent-evidence", "POST", "/api/tasks/{id}/lease/agent-evidence",
            "Record structured agent evidence on an active lease.",
            "AgentEvidenceRequest", "ExecutionLease", true),
        new("lease-recover", "POST", "/api/tasks/{id}/lease/recover",
            "Recover a blocked or failed lease.",
            "RecoverLeaseRequest", "ExecutionLease", false),
        new("lease-fail", "POST", "/api/tasks/{id}/lease/fail",
            "Record dispatch or execution failure evidence.",
            "FailLeaseRequest", "ExecutionLease", true),
        new("lease-dispatch-retry", "POST", "/api/tasks/{id}/lease/dispatch-retry",
            "Retry dispatch for a failed lease.",
            "DispatchRetryRequest", "ExecutionLease", false),
        new("hermes-sync-credentials", "POST", "/api/hermes/sync-credentials",
            "Sync Hermes credentials from install root.",
            null, "HermesSyncCredentialsResponse", false),
        new("agent-manifest-http", "GET", "/api/agent/manifest",
            "Return the static Agent Operations manifest over HTTP.",
            null, "AgentOperationsManifest", true),
        new("agent-endpoints-http", "GET", "/api/agent/endpoints",
            "Return the typed endpoint registry; use ?agentSafe=true for agent-safe routes only.",
            null, "JoyZoningEndpointDescriptor[]", true),
        new("agent-context-http", "GET", "/api/agent/context",
            "Return control-plane runtime state for agents (sessions, leases, approvals).",
            null, "AgentOperationsContextResponse", true),
    ];
}
